version: '3.5'

services:

  # Database
  postgis:
    build:
      context: ./db/
      args:
        LION: 19b
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./db/lion:/lion # downloaded lion data
      - ./db/scripts:/scripts

  # Flask API
  api:
    build:
      context: ./api/
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - postgis
    volumes:
     - ./api:/api

  # Frontend
  client:
    build:
      context: ./client/
    ports:
      - 3000:3000
    depends_on:
      - api
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - '.:/app'
      - '/app/node_modules'

volumes:
    postgresql:
    postgresql_data: