services:

  db:
    image: pgrouting/pgrouting:17-3.5-3.8
    ports:
      - 5433:5432
    env_file:
      - ./docker/dev/.env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  api:
    build:
      context: ./api/
      dockerfile: ../docker/dev/api.Dockerfile
    platform: "linux/amd64"
    ports:
      - 5001:5000
    env_file:
      - ./docker/dev/.env
    volumes:
      - ./api:/home/api
      - ./data-importer:/data-imports
    depends_on:
      - db

  client:
    build:
      context: ./client/
      dockerfile: ../docker/dev/client.Dockerfile
    env_file:
      - ./docker/dev/.env
    ports:
      - 3002:3000
    depends_on:
      - api
    volumes:
      - ./client:/app

volumes:
    postgresql:
    postgresql_data: