version: '3.5'

services:

  db:
    image: pgrouting/pgrouting:12-3.0-master
    ports:
      - 5433:5432
    env_file:
      - ./docker/dev/.env
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  data-importer:
    build:
      context: ./data-importer/
      dockerfile: ../docker/dev/data-importer.Dockerfile
    env_file:
      - ./docker/dev/.env
    volumes:
      - ./data-importer:/data-imports
    depends_on:
      - db

  api:
    build:
      context: ./api/
      dockerfile: ../docker/dev/api.Dockerfile
    ports:
      - 5001:5000
    env_file:
      - ./docker/dev/.env
    volumes:
      - ./api:/api
    depends_on:
      - db


  client:
    build:
      context: ./client/
      dockerfile: ../docker/dev/client.Dockerfile
    env_file:
      - ./docker/dev/.env
    ports:
      - 3001:3000
    depends_on:
      - api
    volumes:
      - ./client:/app

volumes:
    postgresql:
    postgresql_data: